"""empty message

Revision ID: 5a54c8dc947c
Revises: c068d03fe8b8
Create Date: 2018-04-21 23:10:19.363964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a54c8dc947c'
down_revision = 'c068d03fe8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('students', 'student_id')
    op.add_column('tutors', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('tutors', 'tutor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutors', sa.Column('tutor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('tutors', 'id')
    op.add_column('students', sa.Column('student_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('students', 'id')
    # ### end Alembic commands ###
