"""empty message

Revision ID: 69305677efff
Revises: 37dfbd8a898b
Create Date: 2018-04-26 14:35:11.125709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69305677efff'
down_revision = '37dfbd8a898b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('tutor_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('matches')
    # ### end Alembic commands ###
