"""empty message

Revision ID: eca3d3c8561c
Revises: 7d74411719be
Create Date: 2018-04-21 23:04:55.827863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eca3d3c8561c'
down_revision = '7d74411719be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('students', 'student_id')
    op.add_column('tutors', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('tutors', 'tutor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutors', sa.Column('tutor_id', mysql.INTEGER(display_width=11), nullable=False))
    op.drop_column('tutors', 'id')
    op.add_column('students', sa.Column('student_id', mysql.INTEGER(display_width=11), nullable=False))
    op.drop_column('students', 'id')
    # ### end Alembic commands ###
